// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmzHJBA5Y3jOGUrIhBO7gzczCvjmRrTS0',
    appId: '1:404454888428:web:aef6dad19d925a2339a6c9',
    messagingSenderId: '404454888428',
    projectId: 'food-delivery-ece42',
    authDomain: 'food-delivery-ece42.firebaseapp.com',
    storageBucket: 'food-delivery-ece42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjA3tEUFCAb9tsAKefMQDpDvqKY1vTHR8',
    appId: '1:404454888428:android:297750c7b06aee8239a6c9',
    messagingSenderId: '404454888428',
    projectId: 'food-delivery-ece42',
    storageBucket: 'food-delivery-ece42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgJSEmh5odK_CuI8Ax4-RoXIF9bm3dSKE',
    appId: '1:404454888428:ios:b699d62dd0b69e4e39a6c9',
    messagingSenderId: '404454888428',
    projectId: 'food-delivery-ece42',
    storageBucket: 'food-delivery-ece42.appspot.com',
    iosBundleId: 'com.example.stationaryApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgJSEmh5odK_CuI8Ax4-RoXIF9bm3dSKE',
    appId: '1:404454888428:ios:bf493b521c0c985c39a6c9',
    messagingSenderId: '404454888428',
    projectId: 'food-delivery-ece42',
    storageBucket: 'food-delivery-ece42.appspot.com',
    iosBundleId: 'com.example.stationaryApplication.RunnerTests',
  );
}
